# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9c6430081edc577bddae3f32614e2b21e8527fd085d4e42716f0d4e9c2206e0967d0577d741c2b9a0b002ea155fa3b8c37f5ac3ce83618d18ab39a99bd81864

test:
  secret_key_base: c08136f6802be68e23d972b7689b2ade61b3b1f3eb5bc1d5ad6d210dc739282ef5faf706a56a81f4c26b581c3ff4cef8700208107c8ad044b56a04ffd68487d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
